fix createRoom of ChatService with SQL Error(duplicate entry) - find by postId and GuestUserId. postId without HostUserId works well
- fix duplicate entry error by change mapping relation to only saving key
 : SQL Error: 1062, SQLState: 23000
   2024-02-29T17:33:36.875+09:00 ERROR 9096 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Duplicate entry '1' for key 'lost_chat_room.UK_a987gd49jnboa461lfm2qlv1c'
   2024-02-29T17:33:36.920+09:00 ERROR 9096 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.DataIntegrityViolationException: could not execute statement [Duplicate entry '1' for key 'lost_chat_room.UK_a987gd49jnboa461lfm2qlv1c'] [insert into lost_chat_room (guest_user_id,host_user_id,post_id,type) values (?,?,?,?)]; SQL [insert into lost_chat_room (guest_user_id,host_user_id,post_id,type) values (?,?,?,?)]; constraint [lost_chat_room.UK_a987gd49jnboa461lfm2qlv1c]] with root cause

   java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'lost_chat_room.UK_a987gd49jnboa461lfm2qlv1c'